/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PodcastEpisode = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'audio' : ExternalBlob,
  'description' : IDL.Text,
});
export const PodcastView = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'episodes' : IDL.Vec(PodcastEpisode),
  'host' : IDL.Text,
  'description' : IDL.Text,
});
export const TrackNoAlbum = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'audio' : ExternalBlob,
  'artist' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PlaylistView = IDL.Record({
  'tracks' : IDL.Vec(TrackNoAlbum),
  'name' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'theme' : IDL.Text,
  'verified' : IDL.Bool,
  'name' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const Time = IDL.Int;
export const Section = IDL.Variant({
  'music' : IDL.Null,
  'messages' : IDL.Null,
  'podcasts' : IDL.Null,
  'posts' : IDL.Null,
  'reels' : IDL.Null,
});
export const Comment = IDL.Record({
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const PostView = IDL.Record({
  'id' : IDL.Text,
  'author' : IDL.Principal,
  'likes' : IDL.Vec(IDL.Principal),
  'timestamp' : Time,
  'caption' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'sections' : IDL.Vec(Section),
  'comments' : IDL.Vec(Comment),
});
export const Message = IDL.Record({
  'text' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addPodcast' : IDL.Func([PodcastView], [], []),
  'addTrack' : IDL.Func([TrackNoAlbum], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPlaylist' : IDL.Func([IDL.Text], [PlaylistView], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeed' : IDL.Func([IDL.Principal], [IDL.Vec(PostView)], ['query']),
  'getMusicLibrary' : IDL.Func([], [IDL.Vec(TrackNoAlbum)], ['query']),
  'getPodcasts' : IDL.Func([], [IDL.Vec(PodcastView)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text, Message], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PodcastEpisode = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'audio' : ExternalBlob,
    'description' : IDL.Text,
  });
  const PodcastView = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'episodes' : IDL.Vec(PodcastEpisode),
    'host' : IDL.Text,
    'description' : IDL.Text,
  });
  const TrackNoAlbum = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'audio' : ExternalBlob,
    'artist' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PlaylistView = IDL.Record({
    'tracks' : IDL.Vec(TrackNoAlbum),
    'name' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'theme' : IDL.Text,
    'verified' : IDL.Bool,
    'name' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const Time = IDL.Int;
  const Section = IDL.Variant({
    'music' : IDL.Null,
    'messages' : IDL.Null,
    'podcasts' : IDL.Null,
    'posts' : IDL.Null,
    'reels' : IDL.Null,
  });
  const Comment = IDL.Record({
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const PostView = IDL.Record({
    'id' : IDL.Text,
    'author' : IDL.Principal,
    'likes' : IDL.Vec(IDL.Principal),
    'timestamp' : Time,
    'caption' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'sections' : IDL.Vec(Section),
    'comments' : IDL.Vec(Comment),
  });
  const Message = IDL.Record({
    'text' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addPodcast' : IDL.Func([PodcastView], [], []),
    'addTrack' : IDL.Func([TrackNoAlbum], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPlaylist' : IDL.Func([IDL.Text], [PlaylistView], []),
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeed' : IDL.Func([IDL.Principal], [IDL.Vec(PostView)], ['query']),
    'getMusicLibrary' : IDL.Func([], [IDL.Vec(TrackNoAlbum)], ['query']),
    'getPodcasts' : IDL.Func([], [IDL.Vec(PodcastView)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text, Message], [], []),
  });
};

export const init = ({ IDL }) => { return []; };